# Generated by Django 3.2.3 on 2021-05-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0021_auto_20210529_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='settings',
            field=models.JSONField(default=dict, verbose_name='Settings'),
        ),
    ]
