# Generated by Django 3.2.7 on 2021-09-05 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0022_member_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifierSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unbenannte Quelle', max_length=50, verbose_name='Name')),
                ('url', models.URLField(verbose_name='URL')),
                ('frequency', models.CharField(choices=[('hour', 'Stündlich'), ('minute', 'Minütlich')], default='hour', max_length=8, verbose_name='Abfragehäufigkeit')),
                ('last_hash', models.CharField(editable=False, max_length=32, verbose_name='Letzter Hash')),
            ],
            options={
                'verbose_name': 'NotifierSource',
                'verbose_name_plural': 'NotifierSources',
            },
        ),
        migrations.CreateModel(
            name='NotifierTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_contain_regex', models.CharField(blank=True, default='', max_length=32, verbose_name='Muss Regex enthalten')),
                ('where_type', models.CharField(choices=[('channel', 'Kanal'), ('member', 'Mitglied (DM)')], max_length=8, verbose_name='Wohin: Typ')),
                ('where_id', models.CharField(max_length=32, verbose_name='Wohin: ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='discordbot.notifiersource')),
            ],
            options={
                'verbose_name': 'NotifierTarget',
                'verbose_name_plural': 'NotifierTargets',
            },
        ),
        migrations.DeleteModel(
            name='NotifierSub',
        ),
    ]
