# Generated by Django 4.1 on 2022-08-19 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discordbot", "0023_auto_20210905_1703"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BotPermission",
        ),
    ]
