# Generated by Django 5.0.5 on 2024-05-06 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discordbot", "0024_delete_botpermission"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AmongUsGame",
        ),
    ]
